# Generated by Django 3.2 on 2022-08-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sluf',
            new_name='slug',
        ),
    ]
