# Generated by Django 3.2 on 2022-08-30 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
